seed: 1234
cuda_device: 0

train_file: "./data/smiler/en_corpora_train.json"
eval_file: "./data/smiler/de_corpora_test.json"
tag_set_transfer: False

model: google/mt5-base

max_length: 256
batch_size: 16
lr: 3.e-5
num_epochs: 10
